version: '3.3'

services:
  mlflow:
    build: mlflow
    command: sh -c 'mlflow server --backend-store-uri $${BACKEND_URI} --default-artifact-root $${ARTIFACT_URI} --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    environment:
      - TZ=America/New_York
    env_file: 
      - .env
  backend:
    build:
      context: .
      dockerfile: ./backend-flask/Dockerfile
    environment:
      - IN_DOCKER=true
      - PROMETHEUS_MULTIPROC_DIR=prometheus_multiproc_dir
    env_file: 
      - .env
    ports:
      - 9696:9696
      - 9797:9797
    depends_on: 
      - mlflow
  example-prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./backend-flask/monitoring-configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  example-grafana:
    image: grafana/grafana:latest
    user: "472"
    ports:
      - 3000:3000
    volumes:
      - ./backend-flask/monitoring-configs/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./backend-flask/monitoring-configs/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./backend-flask/monitoring-configs/dashboards:/opt/grafana/dashboards
    depends_on:
      - example-prometheus