# config file version
apiVersion: 1

# list of datasources to insert/update, available in database
datasources:
  - name: PostgresSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: monitoring
    user: admin
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'
